apiVersion: v1
kind: Service
metadata:
  name: ark-valg-service
  labels:
    app: ark-valg-service
spec:
  type: NodePort
  ports:
  - port: 29021 # Internal service entrypoint inside the cluster
    targetPort: 31021 # What to hit on the target container
    nodePort: 31021 # External service entrypoint to get *into* the cluster along with a node IP
    protocol: UDP
    name: ark-valg-client # This is the regular client connect port
  - port: 29022
    targetPort: 31022
    nodePort: 31022
    protocol: UDP
    name: ark-valg-raw # This is the "raw" client connect port whatever that means
  - port: 29023
    targetPort: 31023
    nodePort: 31023
    protocol: UDP
    name: ark-valg-steam # This supports the Steam server browser
  - port: 29024
    targetPort: 31024
    nodePort: 31024
    protocol: TCP
    name: ark-valg-rcon # For remote admin
  selector:
    app: arkvalguero
