apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkvalguero
  labels:
    app: arkvalguero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkvalguero
  template:
    metadata:
      labels:
        app: arkvalguero
    spec:
      containers:
      - image: nightdragon1/ark-docker
        name: arkgame
        resources:
          requests:
            cpu: 350m
            memory: 7.25Gi
          limits:
            cpu: 2000m
            memory: 10Gi
        env:
          # Server Parameters
        - name: SESSIONNAME
          value: KubicArk - Valguero
        - name: STEAMPORT # Bad name? is actually the general connect port (27015 is for Steam, yet named SERVERPORT in the Docker image - fix?)
          value: "31022" # Actually unsure if this should be the default 7777 or 7778 (that one, opens a -1 port too) - Docker image defaults to 7778, raw UDP.
        - name: SERVERPORT # This is really the Steam query port
          value: "31023"  # Must be in quotes since it is meant as a value to put into an environment variable
        - name: RCONPORT
          value: "31024"
        - name: SERVERMAP
          value: Valguero_P # TheIsland, TheCenter, ScorchedEarth_P, Ragnarok, Aberration_P, Extinction, Valguero_P, Genesis, CrystalIsles
              # Short names:  islan      cent       scorc            rag       ab            ext         valg        gen1     cryst
        - name: SERVERPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: serverPass
        - name: ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: adminPass
        ports:
            # Note: Query Port cannot be between 27020 and 27050 due to Steam using those ports - shouldn't matter if just changing via Service
          - containerPort: 31021
            protocol: UDP
            name: ark-valg-client
          - containerPort: 31022
            protocol: UDP
            name: ark-valg-raw
          - containerPort: 31023
            protocol: UDP
            name: ark-valg-steam
          - containerPort: 31024
            protocol: TCP
            name: ark-valg-rcon
        volumeMounts:
        - name: ark-valg-persistent-storage
          mountPath: /ark
        - name: ark-persistent-shared-storage
          mountPath: /ark-shared
        - name: ark-valg-config-volume
          mountPath: /ark-config

      # Use an init container to help prepare some config files before the main container starts
      initContainers:
        - name: kubic-ark-prep-container
          image: busybox:1.28
          volumeMounts:
          - name: ark-valg-persistent-storage
            mountPath: /ark
          - name: ark-valg-config-volume
            mountPath: /ark-config
          - name: ark-persistent-shared-storage
            mountPath: /ark-shared
          command: ['sh', '-c']
          args:
            - cd /ark-config;
              ls -la;
              rm -f /ark/MergedGameUserSettings.ini /ark/MergedGame.ini /ark/arkmanager.cfg /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/Game.ini /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              cat GlobalGameUserSettings.ini >> /ark/MergedGameUserSettings.ini;
              echo "" >> /ark/MergedGameUserSettings.ini;
              cat OverrideGameUserSettings.ini >> /ark/MergedGameUserSettings.ini;
              echo "" >> /ark/MergedGameUserSettings.ini;
              cat GlobalGame.ini >> /ark/MergedGame.ini;
              echo "" >> /ark/MergedGame.ini;
              cat OverrideGame.ini >> /ark/MergedGame.ini;
              echo "" >> /ark/MergedGame.ini;
              mkdir -p /ark/server/ShooterGame/Saved/Config/LinuxServer;
              cd /ark;
              ln -s /ark-config/arkmanager.cfg arkmanager.cfg ;
              ln -s /ark-config/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt;
              mkdir -p /ark/server/ShooterGame/Binaries/Linux/;
              ln -s /ark-config/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt;
              ln -s /ark-config/PlayersExclusiveJoinList.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              chmod 777 -R /ark-shared/
      volumes:
      - name: ark-valg-persistent-storage
        persistentVolumeClaim:
          claimName: ark-valg-pv-claim
      - name: ark-persistent-shared-storage
        persistentVolumeClaim:
          claimName: ark-shared-pv-claim
      - name: ark-valg-config-volume
        projected:
          sources:
          - configMap:
              name: ark-global-user-settings-cm
          - configMap:
              name: ark-valg-override-user-settings-cm
          - configMap:
              name: ark-global-game-ini-cm
          - configMap:
              name: ark-valg-override-game-ini-cm
          - configMap:
              name: ark-manager-cm
          - configMap:
              name: ark-player-lists-cm
