apiVersion: v1
kind: Service
metadata:
  name: ark-valg-service
  labels:
    app: ark-valg-service
spec:
  type: NodePort
  ports:
  - port: 29011 # Internal service entrypoint inside the cluster
    targetPort: 31011 # What to hit on the target container
    nodePort: 31011 # External service entrypoint to get *into* the cluster along with a node IP
    protocol: UDP
    name: ark-valg-client # This is the regular client connect port
  - port: 29012
    targetPort: 31012
    nodePort: 31012
    protocol: UDP
    name: ark-valg-raw # This is the "raw" client connect port whatever that means
  - port: 29013
    targetPort: 31013
    nodePort: 31013
    protocol: UDP
    name: ark-valg-steam # This supports the Steam server browser
  - port: 29014
    targetPort: 31014
    nodePort: 31014
    protocol: TCP
    name: ark-valg-rcon # For remote admin
  selector:
    app: arkvalguero
