apiVersion: batch/v1
kind: Job
metadata:
  name: arkvalguerobackup
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: backup-container
          image: busybox:1.28
          volumeMounts:
            - name: ark-valguero-persistent-storage
              mountPath: /ark
          command: ['sh', '-c']
          # Simply make a tar of the desired ARK files and leave them in place for some other process to grab
          args:
            - cd /ark/server/ShooterGame/Saved/SavedArks;
              ls -la;
              rm -f valguero_backup.tar.gz;
              find \( -name Valguero_P.ark -o -name '*.arkprofile' -o -name '*.arktribe' -o -name ServerPaintingsCache \) | sed s,^./,, | tar cfz valguero_backup_backup.tar.gz -C ./ -T -;
              ls -la;
              echo "Sleeping for a minute to allow somebody to come grab this file before exiting";
              sleep 60;
      volumes:
        - name: ark-valguero-persistent-storage
          persistentVolumeClaim:
            claimName: ark-valguero-pv-claim
