apiVersion: v1
kind: Service
metadata:
  name: ark-gen1-service
  labels:
    app: ark-gen1-service
spec:
  type: LoadBalancer
  ports:
  - port: 27015
    targetPort: 27015
    protocol: UDP
    name: ark-gen1-steam # This supports the Steam server browser
  - port: 7776
    targetPort: 7776
    protocol: UDP
    name: ark-gen1-clien1 # This is for regular direct connections?
  - port: 7777
    targetPort: 7777
    protocol: UDP
    name: ark-gen1-client # This is for regular direct connections?
  - port: 7778
    targetPort: 7778
    protocol: UDP
    name: ark-gen1-raw # This should always be client port + 1
  - port: 7779
    targetPort: 7779
    protocol: UDP
    name: ark-gen1-clien2 # This is for regular direct connections?
  - port: 32330
    targetPort: 32330
    protocol: TCP
    name: ark-gen1-rcon
  selector:
    app: arkgenesis
