apiVersion: apps/v1
kind: Deployment
metadata:
  name: ark-valguero
  labels:
    app: ark-valguero
spec:
  replicas: 1
  selector:
    matchLabels:
      lbtype: external
  template:
    metadata:
      labels:
        lbtype: external
        app: ark-valguero
    spec:
      containers:
      - image: nightdragon1/ark-docker
        name: arkgame
        env:
          # Server Parameters
        - name: SESSIONNAME
          value: KubicArkTestServer
        - name: SERVERMAP
          value: Valguero_P # TheIsland, TheCenter, ScorchedEarth_P, Ragnarok, Aberration_P, Extinction, Genesis, Valguero_P, CrystalIsles
        - name: SERVERPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: serverPass
        - name: ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: adminPass
        ports:
            # Note: Query Port cannot be between 27020 and 27050 due to Steam using those ports - shouldn't matter if just changing via Service
          - containerPort: 27015
            protocol: UDP
            name: ark-valguero-steams
          - containerPort: 7777
            protocol: UDP
            name: ark-valguero-gameclient
          - containerPort: 7778
            protocol: UDP
            name: ark-valguero-gamerawudp
        volumeMounts:
        - name: arkgame-persistent-storage
          mountPath: /ark
        - name: arkgame-persistent-shared-storage
          mountPath: /ark-shared
        - name: arkgame-config-volume
          mountPath: /ark-config

      # Use an init container to help prepare some config files before the main container starts
      initContainers:
        - name: kubic-ark-prep-container
          image: busybox:1.28
          volumeMounts:
          - name: arkgame-persistent-storage
            mountPath: /ark
          - name: arkgame-config-volume
            mountPath: /ark-config
          - name: arkgame-persistent-shared-storage
            mountPath: /ark-shared
          command: ['sh', '-c']
          args:
            - cd /ark-config;
              ls -la;
              rm -f /ark/MergedGameUserSettings.ini /ark/MergedGame.ini /ark/arkmanager.cfg /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/Game.ini /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              cat GlobalGameUserSettings.ini >> /ark/MergedGameUserSettings.ini;
              echo "" >> /ark/MergedGameUserSettings.ini;
              cat OverrideGameUserSettings.ini >> /ark/MergedGameUserSettings.ini;
              echo "" >> /ark/MergedGameUserSettings.ini;
              cat GlobalGame.ini >> /ark/MergedGame.ini;
              echo "" >> /ark/MergedGame.ini;
              cat OverrideGame.ini >> /ark/MergedGame.ini;
              echo "" >> /ark/MergedGame.ini;
              mkdir -p /ark/server/ShooterGame/Saved/Config/LinuxServer;
              cd /ark;
              ln -s /ark-config/arkmanager.cfg arkmanager.cfg ;
              ln -s /ark-config/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt;
              mkdir -p /ark/server/ShooterGame/Binaries/Linux/;
              ln -s /ark-config/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt;
              ln -s /ark-config/PlayersExclusiveJoinList.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              chmod 777 -R /ark-shared/
      volumes:
      - name: arkgame-persistent-storage
        persistentVolumeClaim:
          claimName: arkgame-pv-claim
      - name: arkgame-persistent-shared-storage
        persistentVolumeClaim:
          claimName: arkgame-shared-pv-claim
      - name: arkgame-config-volume
        projected:
          sources:
          - configMap:
              name: ark-global-user-settings-cm
          - configMap:
              name: ark-override-user-settings-cm
          - configMap:
              name: ark-global-game-ini-cm
          - configMap:
              name: ark-override-game-ini-cm
          - configMap:
              name: ark-manager-cm
          - configMap:
              name: ark-player-lists-cm
