apiVersion: v1
kind: Secret
metadata:
  name: ark-server-secrets
type: Opaque
stringData:
  # NOTE: Actually update these *before* you kubectl apply this file. Don't submit the updated file to Git!
  # OR use the unattended-password.yaml file to have Jenkins update passwords as a separate secret to load if found
  # This secret is used by the game server, and if automation applies it then we cant edit it manually first
  # So having the other secret optional means the automation can look for it every time and only apply if found
  serverPass: default
  adminPass: wololo
