apiVersion: v1
kind: Service
metadata:
  name: ark-external-lb
spec:
  type: LoadBalancer
  ports:
  - port: 27015
    targetPort: 27015
    protocol: UDP
    name: ark-valguero-steam
  - port: 7777
    targetPort: 7777
    protocol: UDP
    name: ark-valguero-gameclient
  - port: 7778
    targetPort: 7778
    protocol: UDP
    name: ark-valguero-gamerawudpport
  selector:
    # This trick lets us map several deployments to a single service, just varying the ports
    lbtype: external
