apiVersion: v1
kind: Secret
metadata:
  name: ark-server-secrets
type: Opaque
stringData:
  # NOTE: Actually update these *before* you kubectl apply this file. Don't submit the updated file to Git!
  serverPass: default
  adminPass: wololo
