apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkgame
  labels:
    app: arkgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkgame
  template:
    metadata:
      labels:
        app: arkgame
    spec:
      containers:
      - image: nightdragon1/ark-docker
        name: arkgame
        env:
          # Server Parameters
        - name: SESSIONNAME
          value: KubicArkTestServer
        - name: SERVERMAP
          value: Valguero_P # TheIsland, TheCenter, ScorchedEarth_P, Ragnarok, Aberration_P, Extinction, Genesis, Valguero_P, CrystalIsles
        - name: SERVERPASSWORD
          value: pass
        - name: ADMINPASSWORD
          value: adminpass
        - name: SECRET_PASS1
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: serverPass
        - name: SECRET_PASS2
          valueFrom:
            secretKeyRef:
              name: ark-server-secrets
              key: adminPass
        ports:
            # Note: Query Port cannot be between 27020 and 27050 due to Steam using those ports - shouldn't matter if just changing via Ingress
          - containerPort: 27015
            protocol: UDP
            name: ark-steams
          - containerPort: 7777
            protocol: UDP
            name: ark-gameclient
          - containerPort: 7778
            protocol: UDP
            name: ark-gamerawudp
        volumeMounts:
        - name: arkgame-persistent-storage
          mountPath: /ark
        - name: arkgame-persistent-shared-storage
          mountPath: /ark-shared
        - name: arkgame-config-volume
          mountPath: /ark-config

      # Use an init container to help prepare some config files before the main container starts
      initContainers:
        - name: kubic-ark-prep-container
          image: busybox:1.28
          volumeMounts:
          - name: arkgame-persistent-storage
            mountPath: /ark
          - name: arkgame-config-volume
            mountPath: /ark-config
          command: ['sh', '-c']
          args:
            - cd /ark-config;
              ls -la;
              rm -f /ark/tmp0 /ark/tmp1 /ark/tmp10 /ark/tmp11 /ark/MergedGameUserSettings.ini /ark/MergedGame.ini /ark/arkmanager.cfg /ark/server/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini /ark/server/ShooterGame/Saved/Config/LinuxServer/Game.ini /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              cat OverrideGameUserSettings.ini > /ark/tmp0;
              echo "" >> /ark/tmp0;
              cat GlobalGameUserSettings.ini >> /ark/tmp0;
              echo "" >> /ark/tmp0;
              awk -F "=" '!a[$1]++' /ark/tmp0 > /ark/tmp1 && mv /ark/tmp1 /ark/MergedGameUserSettings.ini && rm /ark/tmp0;
              cat OverrideGame.ini > /ark/tmp10;
              echo "" >> /ark/tmp10;
              cat GlobalGame.ini >> /ark/tmp10;
              echo "" >> /ark/tmp10;
              echo "***MergedGame.ini before streamlining***";
              cat /ark/tmp10;
              awk -F "=" '!a[$1]++' /ark/tmp10 > /ark/tmp11 && mv /ark/tmp11 /ark/MergedGame.ini && rm /ark/tmp10;
              echo "***MergedGame.ini after streamlining***";
              cat /ark/tmp10;
              mkdir -p /ark/server/ShooterGame/Saved/Config/LinuxServer;
              cd /ark;
              ln -s /ark-config/arkmanager.cfg arkmanager.cfg ;
              ln -s /ark-config/AllowedCheaterSteamIDs.txt /ark/server/ShooterGame/Saved/AllowedCheaterSteamIDs.txt;
              mkdir -p /ark/server/ShooterGame/Binaries/Linux/;
              ln -s /ark-config/PlayersJoinNoCheck.txt /ark/server/ShooterGame/Binaries/Linux/PlayersJoinNoCheck.txt;
              ln -s /ark-config/PlayersExclusiveJoinList.txt /ark/server/ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt;
              mkdir -p /ark-shared/cluster;
              ls /ark-shared/cluster;
      volumes:
      - name: arkgame-persistent-storage
        persistentVolumeClaim:
          claimName: arkgame-pv-claim
      - name: arkgame-persistent-shared-storage
        persistentVolumeClaim:
          claimName: arkgame-shared-pv-claim
      - name: arkgame-config-volume
        projected:
          sources:
          - configMap:
              name: ark-global-user-settings-cm
          - configMap:
              name: ark-override-user-settings-cm
          - configMap:
              name: ark-global-game-ini-cm
          - configMap:
              name: ark-override-game-ini-cm
          - configMap:
              name: ark-manager-cm
          - configMap:
              name: ark-player-lists-cm
