apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-shared-pv-claim
spec:
  # Depends on KubicGameServer's setup of a dynamic NFS to provision RWM storage to share between pods
  storageClassName: "nfs" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Must fit within dynamic NFS space available (by end of 2024 this is 20Gi)
