apiVersion: v1
kind: Secret
metadata:
  # This secret is optional, and provided in case you want an unattended install to grab these passwords
  # Apply this file once after adjusting the passwords only locally with kubectl apply -f unattended-password.yaml -n ark
  # After you've applied it then throw away the file edits, don't commit it to Git!
  name: ark-unattended-install-secrets
type: Opaque
stringData:
  serverPass: unattended-override-pass
  adminPass: unattended-override-adminpass
