apiVersion: v1
kind: Service
metadata:
  name: ark-island-service
  labels:
    app: arkisland
spec:
  type: NodePort
  ports:
  - port: 29001
    targetPort: 31001
    nodePort: 31001
    protocol: UDP
    name: ark-island-client
  - port: 29002
    targetPort: 31002
    nodePort: 31002
    protocol: UDP
    name: ark-island-raw
  - port: 29003
    targetPort: 31003
    nodePort: 31003
    protocol: UDP
    name: ark-island-steam
  - port: 29004
    targetPort: 31004
    nodePort: 31004
    protocol: TCP
    name: ark-island-rcon
  selector:
    app: arkisland 