apiVersion: v1
kind: Service
metadata:
  name: ark-scorched-service
  labels:
    app: arkscorched
spec:
  ports:
  - port: 31121
    targetPort: 31121
    protocol: UDP
    name: ark-scorched-client
  - port: 31122
    targetPort: 31122
    protocol: UDP
    name: ark-scorched-raw
  - port: 31123
    targetPort: 31123
    protocol: UDP
    name: ark-scorched-steam
  - port: 31124
    targetPort: 31124
    protocol: TCP
    name: ark-scorched-rcon
  selector:
    app: arkscorched 