apiVersion: v1
kind: Service
metadata:
  name: ark-scorched-service
  labels:
    app: arkscorched
spec:
  type: NodePort
  ports:
  - port: 29111
    targetPort: 31111
    nodePort: 31111
    protocol: UDP
    name: ark-scorched-client
  - port: 29112
    targetPort: 31112
    nodePort: 31112
    protocol: UDP
    name: ark-scorched-raw
  - port: 29113
    targetPort: 31113
    nodePort: 31113
    protocol: UDP
    name: ark-scorched-steam
  - port: 29114
    targetPort: 31114
    nodePort: 31114
    protocol: TCP
    name: ark-scorched-rcon
  selector:
    app: arkscorched 