apiVersion: v1
kind: Service
metadata:
  name: ark-extinction-service
  labels:
    app: arkextinction
spec:
  type: NodePort
  ports:
  - port: 29051
    targetPort: 31051
    nodePort: 31051
    protocol: UDP
    name: ark-extinction-client
  - port: 29052
    targetPort: 31052
    nodePort: 31052
    protocol: UDP
    name: ark-extinction-raw
  - port: 29053
    targetPort: 31053
    nodePort: 31053
    protocol: UDP
    name: ark-extinction-steam
  - port: 29054
    targetPort: 31054
    nodePort: 31054
    protocol: TCP
    name: ark-extinction-rcon
  selector:
    app: arkextinction 