apiVersion: v1
kind: Service
metadata:
  name: ark-center-service
  labels:
    app: arkcenter
spec:
  type: NodePort
  ports:
  - port: 29071
    targetPort: 31071
    nodePort: 31071
    protocol: UDP
    name: ark-center-client
  - port: 29072
    targetPort: 31072
    nodePort: 31072
    protocol: UDP
    name: ark-center-raw
  - port: 29073
    targetPort: 31073
    nodePort: 31073
    protocol: UDP
    name: ark-center-steam
  - port: 29074
    targetPort: 31074
    nodePort: 31074
    protocol: TCP
    name: ark-center-rcon
  selector:
    app: arkcenter 