apiVersion: v1
kind: Service
metadata:
  name: ark-center-service
  labels:
    app: arkcenter
spec:
  ports:
  - port: 31111
    targetPort: 31111
    protocol: UDP
    name: ark-center-client
  - port: 31112
    targetPort: 31112
    protocol: UDP
    name: ark-center-raw
  - port: 31113
    targetPort: 31113
    protocol: UDP
    name: ark-center-steam
  - port: 31114
    targetPort: 31114
    protocol: TCP
    name: ark-center-rcon
  selector:
    app: arkcenter 