apiVersion: batch/v1
kind: CronJob
metadata:
  name: ark-center-backup
spec:
  schedule: "0 */4 * * *"  # Every 4 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: google/cloud-sdk:slim
            command:
            - /bin/sh
            - -c
            - |
              gsutil cp gs://kubic-game-hosting/ark/center/$(date +%Y%m%d-%H%M%S)/center_backup.tar.gz gs://kubic-game-hosting/ark/center/$(date +%Y%m%d-%H%M%S)/center_backup.tar.gz
          restartPolicy: OnFailure 