apiVersion: v1
kind: Service
metadata:
  name: ark-crystal-service
  labels:
    app: arkcrystal
spec:
  type: NodePort
  ports:
  - port: 29061
    targetPort: 31061
    nodePort: 31061
    protocol: UDP
    name: ark-crystal-client
  - port: 29062
    targetPort: 31062
    nodePort: 31062
    protocol: UDP
    name: ark-crystal-raw
  - port: 29063
    targetPort: 31063
    nodePort: 31063
    protocol: UDP
    name: ark-crystal-steam
  - port: 29064
    targetPort: 31064
    nodePort: 31064
    protocol: TCP
    name: ark-crystal-rcon
  selector:
    app: arkcrystal 