apiVersion: v1
kind: Service
metadata:
  name: ark-aberration-service
  labels:
    app: arkaberration
spec:
  type: NodePort
  ports:
  - port: 29041
    targetPort: 31041
    nodePort: 31041
    protocol: UDP
    name: ark-aberration-client
  - port: 29042
    targetPort: 31042
    nodePort: 31042
    protocol: UDP
    name: ark-aberration-raw
  - port: 29043
    targetPort: 31043
    nodePort: 31043
    protocol: UDP
    name: ark-aberration-steam
  - port: 29044
    targetPort: 31044
    nodePort: 31044
    protocol: TCP
    name: ark-aberration-rcon
  selector:
    app: arkaberration 