apiVersion: v1
kind: Service
metadata:
  name: ark-ragnarok-service
  labels:
    app: arkragnarok
spec:
  type: NodePort
  ports:
  - port: 29101
    targetPort: 31101
    nodePort: 31101
    protocol: UDP
    name: ark-ragnarok-client
  - port: 29102
    targetPort: 31102
    nodePort: 31102
    protocol: UDP
    name: ark-ragnarok-raw
  - port: 29103
    targetPort: 31103
    nodePort: 31103
    protocol: UDP
    name: ark-ragnarok-steam
  - port: 29104
    targetPort: 31104
    nodePort: 31104
    protocol: TCP
    name: ark-ragnarok-rcon
  selector:
    app: arkragnarok 