apiVersion: v1
kind: ConfigMap
metadata:
  name: ark-ragnarok-override-user-settings-cm
data:
  OverrideGameUserSettings.ini: |-
    [MessageOfTheDay]
    Duration=20
    Message=Welcome to Ragnarok! A Viking-themed world of ancient ruins and mythical creatures awaits. 